feat: add stop and vehicle actions
kiel-live/kiel-live pull request #277
Opened 2024-08-21 10:37 UTC by anbraten

2024-09-05 07:57 UTC, lukashass requested changes
@anbraten why are the action buttons blue and not red?

2024-09-05 07:57 UTC, lukashass commented on app/src/components/popups/Actions.vue
> +          <button
a and button should not be nested

2024-09-07 12:18 UTC, anbraten commented on app/src/components/popups/Actions.vue
> +          <button
changed code to use our existing button

2024-09-07 12:19 UTC, anbraten commented
![image](https://github.com/user-attachments/assets/bdb93f87-2376-4c3a-8b2b-5878e6bfcef8)

![image](https://github.com/user-attachments/assets/045b1558-9de0-4d13-bcd6-c6aaf4aa899e)

2024-09-07 18:38 UTC, lukashass approved these changes

2024-09-07 18:38 UTC, merged